import 'package:get/get.dart';

import '../../config/config.dart';

class ApprovalJson {
  ApprovalJson._privateConstructor();

  static final ApprovalJson _instance = ApprovalJson._privateConstructor();

  factory ApprovalJson() => _instance;

  static designationFormFields(String formName) {
    switch (formName) {
      case 'approvaltemplate':
        return {
          "rightsidebarsize": ModelClassSize.md,
          "pagename": 'approvaltemplate',
          "formname": 'Approval Template',
          "alias": 'approvaltemplate',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "",
              "formFields": [
                {
                  'field': 'name',
                  'text': 'Template Name',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                },
              ]
            },

            {
              "formFields": [
                {
                  'field': 'constructionstageid',
                  'text': 'Construction Stage',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'constructionstage',
                  'masterdatafield': 'name',
                  'formdatafield': 'constructionstage',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'istablefield': true,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'approvalcategoryid',
                  'text': 'Approval',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'approvalcategory',
                  'masterdatafield': 'name',
                  'formdatafield': 'approvalcategory',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'istablefield': true,
                  'onchangedata': ['approvalcategoryid'],
                  'onchangefill': ['subapprovalcategoryid'],
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'subapprovalcategoryid',
                  'text': 'Sub Approval',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'subapprovalcategory',
                  'masterdatafield': 'name',
                  'formdatafield': 'subapprovalcategory',
                  'cleanable': true,
                  'searchable': true,
                  'dependentfilter': {
                    'approvalcategoryid': 'approvalcategoryid',
                  },
                  'istablefield': true,
                  "masterdatadependancy": true,
                  'staticfilter': {"status": 1},
                  'primaryField': true,
                },
                {
                  'field': 'governmentauthorityid',
                  'text': 'Government Authority',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'governmentauthority',
                  'masterdatafield': 'name',
                  'formdatafield': 'governmentauthority',
                  'cleanable': true,
                  'searchable': true,
                  'istablefield': true,
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'frequencyduration',
                  'text': 'Frequency',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'istablefield': true,
                },
                {
                  'field': 'frequencyunit',
                  'text': 'frequencyunit',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': false,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'istablefield': true,
                },{
                  'field': 'frequencyunitid',
                  'text': 'frequencyunitid',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': false,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'istablefield': true,
                },{
                  'field': 'frequency',
                  'text': 'frequency',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': false,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'istablefield': true,
                },
                {
                  'field': 'approvals',
                  'text': 'Add',
                  'type': HtmlControls.kTableAddButton,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'istablefield': true,
                },
                {
                  'field': 'approvals',
                  'text': 'Approvals',
                  'type': HtmlControls.kTable,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k400,
                  'height': 400,
                  "fieldorder": const [
                    {
                      "field": "constructionstageid",
                      "text": "Construction stage",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "constructionstage",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10,
                    },
                    {
                      "field": "constructionstage",
                      "text": "Construction stage",
                      "type": "text",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "constructionstage",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10,
                    },
                    {
                      "field": "approvalcategoryid",
                      "text": "Approval",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "approvalcategory",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "approvalcategory",
                      "text": "Approval",
                      "type": "text",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "approvalcategory",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "subapprovalcategoryid",
                      "text": "Sub approval",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "subapprovalcategory",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10,
                    },
                    {
                      "field": "subapprovalcategory",
                      "text": "Sub approval",
                      "type": "text",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "subapprovalcategory",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10,
                    },
                    {
                      "field": "governmentauthority",
                      "text": "Government authority",
                      "type": "text",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "governmentauthority",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10
                    },
                    {
                      "field": "governmentauthorityid",
                      "text": "Government authority",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "governmentauthority",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 10
                    },
                    {
                      "field": "frequencyduration",
                      "text": "Frequency",
                      "type": "text",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "frequency",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "frequencyunitid",
                      "text": "frequencyunitid",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "frequency",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "frequencyunit",
                      "text": "frequencyunit",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "frequency",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "frequency",
                      "text": "Frequency",
                      "type": "text",
                      "freeze": 1,
                      "active": 0,
                      "sorttable": 0,
                      "sortby": "frequency",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 8,
                    },
                    {
                      "field": "",
                      "text": "",
                      "type": "delete",
                      "freeze": 1,
                      "active": 1,
                      "sorttable": 0,
                      "sortby": "",
                      "filter": 0,
                      "filterfieldtype": "lookup",
                      "defaultvalue": "",
                      "tblsize": 3,
                    }
                  ],
                },
              ]
            },
            {
              "tab": "Project Assignment",
              "editable": false,
              "formFields": [
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'project',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['building'],
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'building',
                  'text': 'Buildings',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'gridsize': FieldSize.k375,
                  'required': true,
                  'masterdata': 'building',
                  'masterdatafield': 'name',
                  'formdatafield': 'name',
                  'cleanable': true,
                  'searchable': false,
                  'dependentfilter': {
                    'projectid': 'projectid',
                  },
                  "masterdatadependancy": true,
                  'staticfilter': {'status': 1},
                },
              ]
            },
          ]
        };

      case 'uploaddocument':
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'uploaddocument',
          "formname": 'Upload Document',
          "alias": 'uploaddocument',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Upload Document",
              "formFields": [
                {
                  'field': 'document',
                  'text': 'Document',
                  'type': HtmlControls.kFilePicker,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'filetypes': FileTypes.pdfAndImage,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'documenttypeid',
                  'text': 'Type',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'approvals/documenttype',
                  'masterdatafield': 'name',
                  'formdatafield': 'documenttype',
                  'staticfilter': {'status': 1},
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': [],
                },
                {
                  'field': 'date',
                  'text': 'Date',
                  'type': HtmlControls.kDatePicker,
                  'disabled': false,
                  'defaultvisibility': true,
                  'ispastdateselected': false,
                  'required': true,
                  'totalfrequencydays': 'totalfrequencydays',
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'expirydate',
                  'text': 'Expiry Date',
                  'type': HtmlControls.kDatePicker,
                  'disabled': false,
                  'defaultvisibility': true,
                  'ispastdateselected': false,
                  'required': true,
                  'mindatekey': 'date',
                  'gridsize': FieldSize.k400,
                },
              ]
            }
          ]
        };

      case 'projectassign':
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'projectassign',
          "formname": 'Project Assignment',
          "alias": 'projectassign',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "",
              "formFields": [
                {
                  'field': 'approvaltemplate',
                  'text': 'Template Name',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                },
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'project',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['building'],
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'building',
                  'text': 'Buildings',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'gridsize': FieldSize.k375,
                  'required': true,
                  'masterdata': 'building',
                  'masterdatafield': 'name',
                  'formdatafield': 'building',
                  'cleanable': true,
                  'searchable': false,
                  'dependentfilter': {
                    'projectid': 'projectid',
                  },
                  "masterdatadependancy": true,
                  'staticfilter': {'status': 1},
                },
              ]
            }
          ]
        };

      case 'multiprojectassign':
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'projectassign',
          "formname": 'Project Assignment',
          "alias": 'projectassign',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "",
              "formFields": [
                {
                  'field': 'approvaltemplate',
                  'text': 'Template Name',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                },
                {
                  'field': 'project',
                  'text': 'Projects',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'gridsize': FieldSize.k375,
                  'required': true,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'project',
                  'cleanable': true,
                  'searchable': true,
                  "masterdatadependancy": false,
                  'staticfilter': {'status': 1},
                },
              ]
            }
          ]
        };

      case 'addnewapproval':
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'addnewapproval',
          "formname": 'New Approval',
          "alias": 'addnewapproval',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "New Approval",
              "formFields": [
                {
                  'field': 'constructionstageid',
                  'text': 'Construction Stage',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'constructionstage',
                  'masterdatafield': 'name',
                  'formdatafield': 'constructionstage',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'approvalcategoryid',
                  'text': 'Approval',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'approvalcategory',
                  'masterdatafield': 'name',
                  'formdatafield': 'approvalcategory',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'onchangedata': ['approvalcategoryid'],
                  'onchangefill': ['subapprovalcategoryid'],
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'subapprovalcategoryid',
                  'text': 'Sub Approval',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'subapprovalcategory',
                  'masterdatafield': 'name',
                  'formdatafield': 'subapprovalcategory',
                  'cleanable': true,
                  'searchable': true,
                  'dependentfilter': {
                    'approvalcategoryid': 'approvalcategoryid',
                  },
                  "masterdatadependancy": true,
                  'staticfilter': {"status": 1},
                  'primaryField': true,
                },
                {
                  'field': 'governmentauthorityid',
                  'text': 'Government Authority',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'governmentauthority',
                  'masterdatafield': 'name',
                  'formdatafield': 'governmentauthority',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'frequencyduration',
                  'text': 'Renewal Frequency',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                }
              ]
            }
          ]
        };

      default:
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'templateassignment',
          "formname": 'Template Assignment',
          "alias": 'templateassignment',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Add New Template",
              "formFields": [
                {
                  'field': 'approvaltemplateid',
                  'text': 'Template Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'approvaltemplate',
                  'masterdatafield': 'name',
                  'formdatafield': 'approvaltemplate',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'project',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['building'],
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                  'projection': {
                    '_id': 1,
                    'name': 1,
                  },
                },
                {
                  'field': 'building',
                  'text': 'Buildings',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'gridsize': FieldSize.k375,
                  'required': true,
                  'masterdata': 'building',
                  'masterdatafield': 'name',
                  'formdatafield': 'name',
                  'cleanable': true,
                  'searchable': false,
                  'dependentfilter': {
                    'projectid': 'projectid',
                  },
                  "masterdatadependancy": true,
                  'staticfilter': {'status': 1},
                },
                // {
                //   'field': 'buildingid',
                //   'text': 'Building Name',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k400,
                //   'masterdata': 'building',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'buildingname',
                //   'cleanable': true,
                //   'searchable': true,
                //   'onchangedata': ['buildingid'],
                //   'dependentfilter': {
                //     'projectid': 'projectid',
                //   },
                //   'masterdatadependancy': true,
                //   'primaryField': true,
                //   'staticfilter': {'status': 1},
                // },

                {
                  'field': 'status',
                  'text': 'Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'status',
                  'masterdataarray': Config.statusType,
                  'defaultvalue': 1,
                  'formdatafield': 'status',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
              ]
            }
          ]
        };
    }
  }
}
