import '../../config/config.dart';

class ProjectManagementJson {
  ProjectManagementJson._privateConstructor();

  static final ProjectManagementJson _instance = ProjectManagementJson._privateConstructor();

  factory ProjectManagementJson() => _instance;

  static designationFormFields(String formName) {
    switch (formName) {
      case "project":
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'project',
          "formname": 'Project',
          "alias": 'project',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Project",
              "formFields": [
                {
                  'field': 'tenantprojectid',
                  'text': 'Tenant Project',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'tenantproject',
                  'masterdatafield': 'name',
                  'formdatafield': 'tenantprojectname',
                  'cleanable': true,
                  'searchable': true,
                  'staticfilter': {'status': 1},
                  'primaryField': true,
                },
                {
                  'field': 'developername',
                  'text': 'Developer Name',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'primaryField': true,
                },
                {
                  'field': 'name',
                  'text': 'Project Name',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k200,
                  'primaryField': true,
                },
                {
                  'field': 'shortcode',
                  'text': 'Short Code',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k150,
                },
                {
                  'field': 'address1',
                  'text': 'Address Line 1',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'address2',
                  'text': 'Address Line 2',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'pincode',
                  'text': 'Pincode',
                  'type': HtmlControls.kNumberInput,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'maxlength': 6,
                  'minlength': 6,
                },
                {
                  'field': 'pincodeid',
                  'text': 'Area',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'pincode',
                  'masterdatafield': 'area',
                  'formdatafield': 'area',
                  'cleanable': true,
                  'searchable': true,
                  'dependentfilter': {
                    'pincode': 'pincode',
                  },
                  'masterdatadependancy': true,
                  'staticfilter': {
                    'status': 1,
                    'listarea': true,
                  },
                  'condition': {
                    'pincodeNewEntry': [0]
                  }
                },
                {
                  'field': 'city',
                  'text': 'City',
                  'type': HtmlControls.kInputText,
                  'disabled': true,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'condition': {
                    'pincodeNewEntry': [0]
                  }
                },
                {
                  'field': 'area',
                  'text': 'Area',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'condition': {
                    'pincodeNewEntry': [1]
                  }
                },
                {
                  'field': 'cityid',
                  'text': 'City',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'city',
                  'masterdatafield': 'city',
                  'formdatafield': 'city',
                  'cleanable': true,
                  'searchable': true,
                  'staticfilter': {
                    'status': 1,
                  },
                  'condition': {
                    'pincodeNewEntry': [1]
                  }
                },
                {
                  'field': 'constructionstageid',
                  'text': 'Construction Stage',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'constructionstage',
                  'masterdatafield': 'name',
                  'formdatafield': 'constructionstagename',
                  'cleanable': true,
                  'searchable': true,
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'status',
                  'text': 'Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'status',
                  'masterdataarray': Config.statusType,
                  'defaultvalue': 1,
                  'formdatafield': 'status',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
              ]
            }
          ],
        };

      case "building":
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'building',
          "formname": 'Building',
          "alias": 'building',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Building",
              "formFields": [
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'projectname',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                  'primaryField': true,
                },
                {
                  'field': 'name',
                  'text': 'Building Name',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'primaryField': true,
                },
                {
                  'field': 'area',
                  'text': 'Area',
                  'suffixtext': 'Sq. Ft.',
                  'type': HtmlControls.kNumberInput,
                  'decimalpoint': 2,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'status',
                  'text': 'Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'status',
                  'masterdataarray': Config.statusType,
                  'defaultvalue': 1,
                  'formdatafield': 'status',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
              ]
            }
          ],
        };

      case "floor":
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'floor',
          "formname": 'Floor',
          "alias": 'floor',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Floor",
              "formFields": [
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'projectname',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['buildingid'],
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                  'primaryField': true,
                },
                {
                  'field': 'buildingid',
                  'text': 'Building Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'building',
                  'masterdatafield': 'name',
                  'formdatafield': 'buildingname',
                  'cleanable': true,
                  'searchable': true,
                  'dependentfilter': {
                    'projectid': 'projectid',
                  },
                  'masterdatadependancy': true,
                  'staticfilter': {'status': 1},
                  'primaryField': true,
                },
                {
                  'field': 'name',
                  'text': 'Floor Name',
                  'type': HtmlControls.kInputText,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'primaryField': true,
                },
                {
                  'field': 'area',
                  'text': 'Area',
                  'suffixtext': 'Sq. Ft.',
                  'type': HtmlControls.kNumberInput,
                  'decimalpoint': 2,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'status',
                  'text': 'Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'status',
                  'masterdataarray': Config.statusType,
                  'defaultvalue': 1,
                  'formdatafield': 'status',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
              ]
            }
          ],
        };

      case "unit":
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'unit',
          "formname": 'Unit',
          "alias": 'unit',
          "dataview": "tab",
          'formfields': [
            {
              "tab": "Unit",
              "formFields": [
                {
                  'field': 'projectid',
                  'text': 'Project Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'project',
                  'masterdatafield': 'name',
                  'formdatafield': 'projectname',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['buildingid'],
                  'onchangedata': ['projectid'],
                  'masterdatadependancy': false,
                  'primaryField': true,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'buildingid',
                  'text': 'Building Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'building',
                  'masterdatafield': 'name',
                  'formdatafield': 'buildingname',
                  'cleanable': true,
                  'searchable': true,
                  'onchangefill': ['floorid'],
                  'onchangedata': ['buildingid'],
                  'dependentfilter': {
                    'projectid': 'projectid',
                  },
                  'masterdatadependancy': true,
                  'primaryField': true,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'floorid',
                  'text': 'Floor Name',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'floor',
                  'masterdatafield': 'name',
                  'formdatafield': 'floorname',
                  'cleanable': true,
                  'searchable': true,
                  'dependentfilter': {
                    'buildingid': 'buildingid',
                  },
                  'masterdatadependancy': true,
                  'primaryField': true,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'unitnumber',
                  'text': 'Unit Number',
                  'type': HtmlControls.kNumberInput,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'primaryField': true,
                },
                {
                  'field': 'unittypeid',
                  'text': 'Unit Type',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'unittype',
                  'masterdatafield': 'name',
                  'formdatafield': 'unittype',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                  'staticfilter': {'status': 1},
                },
                {
                  'field': 'area',
                  'text': 'Area',
                  'suffixtext': 'Sq. Ft.',
                  'type': HtmlControls.kNumberInput,
                  'decimalpoint': 2,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                },
                {
                  'field': 'unitstatusid',
                  'text': 'Unit Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'unitstatus',
                  'masterdatafield': 'name',
                  'formdatafield': 'unitstatus',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
                {
                  'field': 'status',
                  'text': 'Status',
                  'type': HtmlControls.kDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k400,
                  'masterdata': 'status',
                  'masterdataarray': Config.statusType,
                  'defaultvalue': 1,
                  'formdatafield': 'status',
                  'cleanable': true,
                  'searchable': true,
                  'onchangedata': ['statusid'],
                  'masterdatadependancy': false,
                },
              ]
            }
          ],
        };
    }
  }
}
