import '../../config/config.dart';
import '../../routes/route_name.dart';

class SapTenantHistoryJson {
  SapTenantHistoryJson._privateConstructor();

  static final SapTenantHistoryJson _instance = SapTenantHistoryJson._privateConstructor();

  factory SapTenantHistoryJson() => _instance;

  static designationFormFields(String formName) {
    switch (formName) {
      case 'saptenanterrors':
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'saptenanthistory',
          "formname": 'Sap Logs',
          "dataview": "tab",
          "alias": 'saptenanthistory',
          "formfields": [
            {
              "tab": "Icon",
              "formFields": [
                {
                  'field': 'tenant',
                  'text': 'Tenants',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'tenant',
                  'masterdatafield': 'tenantname',
                  'formdatafield': 'tenant',
                  'cleanable': true,
                  'searchable': true,
                  // 'projection': {
                  //   'tenantname': 1,
                  //   '_id': 1,
                  // }
                  // 'staticfilter': {'status': 1},
                  // 'onchangedata': ['hutmentsupport'],
                  // 'masterdatadependancy': false,
                },
                {
                  'field': 'tenantstatus',
                  'text': 'Tenants Status',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'tenantstatus',
                  'masterdatafield': 'status',
                  'formdatafield': 'tenant',
                  'cleanable': true,
                  'searchable': true,
                  // 'projection': {
                  //   'tenantname': 1,
                  //   '_id': 1,
                  // }
                  // 'staticfilter': {'status': 1},
                  // 'onchangedata': ['hutmentsupport'],
                  // 'masterdatadependancy': false,
                },
                {
                  'field': 'sapoperations',
                  'text': 'SAP Operations',
                  'type': HtmlControls.kMultiSelectDropDown,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': true,
                  'gridsize': FieldSize.k375,
                  'masterdata': 'sapoperations',
                  'masterdatafield': 'label',
                  'formdatafield': 'sapoperations',
                  'cleanable': true,
                  'searchable': true,
                  // 'staticfilter': {'status': 1},
                  // 'onchangedata': ['hutmentsupport'],
                  // 'masterdatadependancy': false,
                },
                {
                  'field': 'daterange',
                  'text': 'Date',
                  'type': HtmlControls.kDateRangePicker,
                  'disabled': false,
                  'defaultvisibility': true,
                  'required': false,
                  'gridsize': FieldSize.k375,
                  'cleanable': true,
                  'searchable': true,
                  // 'staticfilter': {'status': 1},
                  // 'onchangedata': ['hutmentsupport'],
                  // 'masterdatadependancy': false,
                },
                // {
                //   'field': 'tenantproject',
                //   'text': 'Tenant Project Name',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'tenantproject',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'tenantproject',
                //   'cleanable': true,
                //   'searchable': true,
                //   'onchangedata': [
                //     'tenantproject',
                //   ],
                //   'onchangefill': [
                //     'society',
                //   ],
                //   'staticfilter': {'status': 1},
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'hutmentusetype',
                //   'text': 'Hutment Use',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'unittype',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'hutmentusetype',
                //   'cleanable': true,
                //   'searchable': true,
                //   'onchangedata': ['hutmentusetype'],
                //   'staticfilter': {'status': 1},
                //   'masterdatadependancy': false,
                //   'projection': {
                //     '_id': 1,
                //     'name': 1,
                //   }
                // },
                // {
                //   'field': 'eligibility',
                //   'text': 'Eligibility',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': false,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'eligibility',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'eligibility',
                //   'staticfilter': {'status': 1},
                //   'projection': {
                //     '_id': 1,
                //     'name': 1,
                //   },
                //   'cleanable': true,
                //   'searchable': true,
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'society',
                //   'text': 'Society',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': false,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'society',
                //   'masterdatafield': 'tenantname',
                //   'formdatafield': 'society',
                //   'dependentfilter': {
                //     'tenantproject': 'tenantproject',
                //   },
                //   'cleanable': true,
                //   'searchable': true,
                //   'staticfilter': {'status': 1},
                //   // 'masterdatadependancy': true,
                //   'projection': {
                //     '_id': 1,
                //     'tenantname': 1,
                //   }
                // },
                // {
                //   'field': 'hutmentsupport',
                //   'text': 'Hutment Support',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'hutmentsupport',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'hutmentsupport',
                //   'cleanable': true,
                //   'searchable': true,
                //   'staticfilter': {'status': 1},
                //   'onchangedata': ['hutmentsupport'],
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'commonconsent',
                //   'text': 'Common Consent',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'consent',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'commonconsent',
                //   'staticfilter': {'forcommonconsent': 1, 'status': 1},
                //   'cleanable': true,
                //   'searchable': true,
                //   'storemasterdatabyfield': true,
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'individualconsent',
                //   'text': 'Individual Consent',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'consent',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'individualconsent',
                //   'staticfilter': {'forindividualconsent': 1, 'status': 1},
                //   'cleanable': true,
                //   'searchable': true,
                //   'storemasterdatabyfield': true,
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'individualagreement',
                //   'text': 'Individual Agreement',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': true,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'consent',
                //   'masterdatafield': 'name',
                //   'formdatafield': 'individualagreement',
                //   'staticfilter': {'forindividualagreement': 1, 'status': 1},
                //   'cleanable': true,
                //   'searchable': true,
                //   'storemasterdatabyfield': true,
                //   'masterdatadependancy': false,
                // },
                // {
                //   'field': 'tenantstatus',
                //   'text': 'Hutment Status',
                //   'type': HtmlControls.kMultiSelectDropDown,
                //   'disabled': false,
                //   'defaultvisibility': true,
                //   'required': false,
                //   'gridsize': FieldSize.k375,
                //   'masterdata': 'tenantstatus',
                //   'masterdatafield': 'status',
                //   'formdatafield': 'tenantstatus',
                //   'cleanable': true,
                //   'staticfilter': {'status': 1},
                //   'searchable': true,
                //   'masterdatadependancy': false,
                //   'projection': {
                //     '_id': 1,
                //     'status': 1,
                //   },
                // }
              ]
            },
          ]
        };
      default:
        return {
          "rightsidebarsize": ModelClassSize.xs,
          "pagename": 'this is default case',
          "formname": 'this is default case executed...',
          "alias": 'this is default case executed...',
          "dataview": "tab",
          'formfields': [
            {"tab": "this is default case executed...", "formFields": []}
          ],
        };
    }
  }
}
